name: Update Fed Forecast

on:
  schedule:
    - cron: '0 6 * * *'  # Every day at 6am UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install axios

      - name: Run forecast script
        run: |
          echo "const axios = require('axios'); const fs = require('fs');" > fetch.js
          curl -s https://gist.githubusercontent.com/YOUR_GIST_ID/raw/fetch-fed-futures.js >> fetch.js
          node fetch.js

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add fed_forecast.json
          git commit -m "Daily update"
          git push
